AWSTemplateFormatVersion: '2010-09-09'

Description: "This template creates an S3 bucket"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket-nowmonthe
 
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0557a15b87f6559cf # Amazon Linux 2 LTS
      InstanceType: t2.micro
      KeyName: monthe
      SecurityGroups:
        - !Ref EC2InstanceSecurityGroup
  EC2InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
